
export const bagtypes = [
  "Handbags",
  "Shoulder Bags",
  "Luggage & Travel Bags",
  "Backpacks",
  "Suitcases",
  "Ankara Bags",
  "Art & Poster Tubes",
  "Baby & Diaper Bags",
  "Badminton Bags",
  "Bags Accessories",
  "Baguette Bags",
  "Barrel Bags",
  "Beach Bags",
  "Bicycle Frame Bags",
  "Bra & Lingerie Travel Cases",
  "Brady Bags",
  "Briefcases",
  "Bucket Bags",
  "Business Bags",
  "Camera Bags",
  "Card Holders",
  "Carry-All Bags",
  "Chain Bags",
  "Clothes Storage Bags",
  "Clutches",
  "Crossbody Bags",
  "Cycling Bags",
  "Delivery Bags",
  "Doctor Bags",
  "Drawstring Bags",
  "Duffle Bags",
  "Envelope Bags",
  "Envelope Clutch Bags",
  "Evening Bags",
  "Fishing Creel Bags",
  "Flap Bags",
  "Flat Bags",
  "Folder Bags",
  "Foldover Bags",
  "Garment Bags",
  "Gift Bags",
  "Golf Bags",
  "Gym & Sport Bags",
  "Hiking Bags",
  "Hobo Bags",
  "Instrument Bags & Cases",
  "Jelly Bags",
  "Laptop Bags & Cases",
  "Lunch Bags",
  "Make-Up Bags & Organizers",
  "Messenger Bags",
  "Mini Bags",
  "Pouch Bags",
  "Roller Skate Bags",
  "Rope Bags",
  "Round Bags",
  "Rucksack",
  "Saddle Bags",
  "School Bags",
  "Shopper Bags",
  "Swagger Bags",
  "Top Handles Bags",
  "Tote Bags",
  "Valise Bags",
  "Waist & Belt Bags",
  "Wallets and Purses",
  "Wristlet Bags",
  "Other"
]






export const storeProducts = [
  {
    id: 1,
    title: 'William Backpack',
    img: '/images/product/bags/1.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
    {
    id: 2,
    title: 'William Backpack',
    img: '/images/product/bags/2.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 3,
    title: 'William Backpack',
    img: '/images/product/bags/3.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 4,
    title: 'William Backpack',
    img: '/images/product/bags/4.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 5,
    title: 'William Backpack',
    img: '/images/product/bags/5.webp',
    price: 4650,
    artist: 'whisky',
    category:'bags',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 6,
    title: 'William Backpack',
    img: '/images/product/bags/6.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 8,
    title: 'William Backpack',
    img: '/images/product/bags/8.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 8,
    title: 'William Backpack',
    img: '/images/product/bags/8.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 9,
    title: 'William Backpack',
    img: '/images/product/bags/9.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 10,
    title: 'William Backpack',
    img: '/images/product/bags/10.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 11,
    title: 'William Backpack',
    img: '/images/product/bags/11.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 12,
    title: 'William Backpack',
    img: '/images/product/bags/12.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 13,
    title: 'William Backpack',
    img: '/images/product/bags/13.webp',
    price: 4650,
    artist: 'whisky',
    category:'bags',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 14,
    title: 'William Backpack',
    img: '/images/product/bags/14.webp',
    price: 4650,
    artist: 'whisky',
    category:'bags',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 15,
    title: 'William Backpack',
    img: '/images/product/bags/15.webp',
    price: 4650,
    artist: 'whisky',
    category:'bags',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 16,
    title: 'William Backpack',
    img: '/images/product/bags/16.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 17,
    title: 'William Backpack',
    img: '/images/product/bags/17.webp',
    price: 4650,
    artist: 'whisky',
    category:'backpack',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
      {
    id: 18,
    title: 'William Backpack',
    img: '/images/product/bags/18.webp',
    price: 4650,
    artist: 'whisky',
    category:'bags',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 19,
    title: 'William Backpack',
    img: '/images/product/bags/19.webp',
    price: 4650,
    artist: 'whisky',
    category:'bags',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 20,
    title: 'William Backpack',
    img: '/images/product/bags/20.webp',
    price: 4650,
    artist: 'whisky',
    category:'bags',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 21,
    title: 'William Backpack',
    img: '/images/product/wallet/1.webp',
    price: 4650,
    artist: 'whisky',
    category:'wallet',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },  
    {
    id: 22,
    title: 'William Backpack',
    img: '/images/product/wallet/2.webp',
    price: 4650,
    artist: 'whisky',
    category:'wallet',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 23,
    title: 'William Backpack',
    img: '/images/product/wallet/3.webp',
    price: 4650,
    artist: 'whisky',
    category:'wallet',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 24,
    title: 'William Backpack',
    img: '/images/product/wallet/4.webp',
    price: 4650,
    artist: 'whisky',
    category:'wallet',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 25,
    title: 'William Backpack',
    img: '/images/product/wallet/5.webp',
    price: 4650,
    artist: 'whisky',
    category:'wallet',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 26,
    title: 'William Backpack',
    img: '/images/product/wallet/6.webp',
    price: 4650,
    artist: 'whisky',
    category:'wallet',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  }
  ,
    {
    id: 27,
    title: 'William Backpack',
    img: '/images/product/wallet/7.webp',
    price: 4650,
    artist: 'whisky',
    category:'wallet',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 28,
    title: 'William Backpack',
    img: '/images/product/wallet/8.webp',
    price: 4650,
    artist: 'whisky',
    category:'wallet',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 29,
    title: 'William Backpack',
    img: '/images/product/belt/10.webp',
    price: 4650,
    artist: 'whisky',
    category:'belt',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 30,
    title: 'William Backpack',
    img: '/images/product/belt/11.webp',
    price: 4650,
    artist: 'whisky',
    category:'belt',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
},
  
    {
    id: 31,
    title: 'William Backpack',
    img: '/images/product/belt/12.webp',
    price: 4650,
    artist: 'whisky',
    category:'belt',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 32,
    title: 'William Backpack',
    img: '/images/product/belt/13.webp',
    price: 4650,
    artist: 'whisky',
    category:'belt',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 33,
    title: 'William Backpack',
    img: '/images/product/belt/14.webp',
    price: 4650,
    artist: 'whisky',
    category:'belt',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 34,
    title: 'William Backpack',
    img: '/images/product/belt/15.webp',
    price: 4650,
    artist: 'whisky',
    category:'belt',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 35,
    title: 'William Backpack',
    img: '/images/product/belt/16.webp',
    price: 4650,
    artist: 'whisky',
    category:'belt',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 36,
    title: 'William Backpack',
    img: '/images/product/belt/18.webp',
    price: 4650,
    artist: 'whisky',
    category:'belt',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  
    {
    id: 37,
    title: 'William Backpack',
    img: '/images/product/image2.jpeg',
    price: 4650,
    artist: 'whisky',
    category:'bags',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
  

    {
    id: 38,
    title: 'William Backpack',
    img: '/images/product/image3.jpeg',
    price: 4650,
    artist: 'whisky',
    category:'bags',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  } ,
  
    {
    id: 39,
    title: 'William Backpack',
    img: '/images/product/image4.jpeg',
    price: 4650,
    artist: 'whisky',
    category:'bags',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  },
    
    {
    id: 40,
    title: 'William Backpack',
    img: '/images/product/image5.jpeg',
    price: 4650,
    artist: 'whisky',
    category:'watch',
    subject:'Flowers and plants',
    info: 'Perfection: A perfect pick for daily use, this Polester Trending Backpack can securely be used to carry mobile phone, cards, cosmetics, iPad, umbrella and other daily essential things in a safe, secure and arranged manner. No matter wherever you are heading to, it can be your companion for every hour of need. Stylish &amp; Fashionable: This bag is designed for modern fashion-conscious individuals who desire style along with functionality. It is a perfect mid-sized bag to carry all the daily essentials while using it as a fashion daypack, mini travel bag, college backpack etc.',
    inCart: false,
    count: 0,
    total: 0,
  }
  


]
